#!/bin/bash

cmake -DCMAKE_INSTALL_PREFIX=$HOME/deal.II/install \
      -DCMAKE_C_COMPILER="gcc" \
      -DCMAKE_CXX_COMPILER="g++" \
      -DDEAL_II_COMPONENT_DOCUMENTATION=OFF \
      -DDEAL_II_COMPONENT_MESH_CONVERTER=ON \
      -DDEAL_II_WITH_UMFPACK=ON \
      -DDEAL_II_WITH_THREADS=ON \
      -DDEAL_II_WITH_TRILINOS=ON \
      -DTRILINOS_DIR=/opt/trilinos-11.4.1 \
      -DDEAL_II_WITH_PETSC=OFF \
      -DDEAL_II_WITH_SLEPC=OFF \
      -DDEAL_II_WITH_MPI=OFF \
      -DDEAL_II_WITH_METIS=OFF \
      ..
